version: '3.8'

services:
  postgres:
    image: postgres:17
    networks:
      - pgnetwork
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka-native:latest
    hostname: kafka
    networks:
      - kafka-bridge
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  redpanda-console:
    image: redpandadata/console:latest
    networks:
      - kafka-bridge
    environment:
      KAFKA_BROKERS: "kafka:9092"
    ports:
      - "8585:8080"
    depends_on:
      - kafka

volumes:
  postgres_data:
    name: multi_currency_wallet_postgres_data_v17
    driver: local

networks:
  kafka-bridge:
    driver: bridge
  pgnetwork:
    driver: bridge


